language: objective-c
osx_image: xcode7.2
# Ugly workaround to compile on OSX/64bits... where SwiftyGPIO will never run... 
before_script:
  - wget https://raw.githubusercontent.com/uraimo/SwiftyGPIO/master/Sources/SwiftyGPIO.swift -P Sources/
  - sed -i ""  s/GPIO_BASE:Int/GPIO_BASE:Int64/ Sources/SwiftyGPIO.swift
  - echo "let O_SYNC:Int32=1052672" > Sources/main.swift
script: files=$(find Sources -regex '.*[^/]swift') && xcrun -sdk macosx swiftc $files
